# Site settings
title: Govinda - Desenvolvedor Full Stack
email: seu-email@exemplo.com
description: >-
  Portfolio profissional de Govinda - Desenvolvedor apaixonado por tecnologia, 
  transformando ideias em soluções inovadoras.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://govinda777.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: true
    permalink: /projetos/:path/
  posts:
    output: true
    permalink: /blog/:title/

# Exclude from processing
exclude:
  - .git/
  - .github/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
